apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo
  namespace: podinfo
spec:
  provider: nginx
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  service:
    port: 9898
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: podinfo
  metricsServer: http://flagger-prometheus.flagger-system:9090
  analysis:
    interval: 1m
    threshold: 10
    maxWeight: 50
    stepWeight: 5
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 1m
    # - name: error-rate
    #   templateRef:
    #     name: error-rate
    #   thresholdRange:
    #     max: 1
    #   interval: 30s
    # - name: latency
    #   templateRef:
    #     name: latency
    #   thresholdRange:
    #     max: 0.5
    #   interval: 30s
    webhooks:
      - name: load-test
        url: http://flagger-loadtester.flagger-system/
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://podinfo-canary.podinfo:9898/"